import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import Drawer from "../Drawer/Drawer";

interface Props {
  title?: string;
  children: ReactNode;
}

const Layout = ({ title = "", children }: Props) => {
  const layoutTitle = `SimpleNotta | ${title ? "| " + title : ""}`;

  return (
    <>
      <Head>
        <title>{layoutTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Drawer>{children}</Drawer>

     
    </>
  );
};

export default Layout;
